# Generated by Django 2.0.5 on 2024-06-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='nm_tv_assets_thumbs')),
                ('file', models.FileField(upload_to='nm_tv_assets_files')),
                ('is_public', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schools_class',
            },
        ),
        migrations.CreateModel(
            name='ClassMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'schools_class_members',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('allow_online_saving', models.NullBooleanField(default=False)),
                ('allow_upload_to_NM', models.NullBooleanField(default=False)),
                ('allow_template', models.NullBooleanField(default=False)),
                ('allow_access_to_asset_store', models.NullBooleanField(default=False)),
                ('additional_assets', models.ManyToManyField(to='tv.Asset')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('tall', 'TALL'), ('wide', 'WIDE')], max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('allowed_functions', models.TextField(blank=True, null=True)),
                ('displayed_image', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('classes_to_share', models.ManyToManyField(blank=True, to='tv.Class')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.AssetLanguage')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.Template')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='templates',
            field=models.ManyToManyField(blank=True, null=True, to='tv.TemplateForSale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.AssetType'),
        ),
    ]
