# Generated by Django 2.0.5 on 2024-06-29 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_nm_api', '0001_initial'),
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_nm_api.TVPresentation')),
            ],
        ),
    ]
