# Generated by Django 2.0.5 on 2024-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_publishqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishqueue',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
